version: "3.5"

services:
  acai_mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: acai_mssqlserver
    hostname: acai_mssqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: teste@123
      MSSQL_AGENT_ENABLED: "true"
    ports:
      - "1434:1433"
    volumes:
      - "acai-sqlserver:/var/lib/sqlserver/data"
  acai_mssqlscripts:
    image: mcr.microsoft.com/mssql-tools
    container_name: acai_mssqlscripts
    hostname: acai_mssqlscripts
    depends_on:
      - acai_mssql
    command: /bin/bash -c 'until /opt/mssql-tools/bin/sqlcmd -S acai_mssqlserver -U sa -P "teste@123" -Q "create database acai_db"; do sleep 5; done'
volumes:
  acai-sqlserver:
